### ISSUE TITLE
discord authorization

### ISSUE THREAD

**Issue by AEnterprise** [gearbot/Dashboard-api#10]
1) user comes on our page, we query /api/whoami to determine login status
2) not authorized, user sees login button
3) login with discord
4) callback inserts auth token into redis for a week, sets a session cookie jwt containing userid
4) we are back on the site, query /api/whoami again
5) we grab the userid from jwt, pass to bot over redis to get userinfo

**Comment by BlackHoleFox** [comment]
I think we can say this is complete :)
